In [1]:
# imports

import pandas as pd
import polars as pl
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# load data into lazyframes

demo = pl.scan_csv("../data/raw/DemoStats_(DST)_2025_2025_GEO.csv", schema_overrides={"CODE": pl.String})
hhs1 = pl.scan_csv("../data/raw/HouseholdSpend_(HHS)_2025_GEO_P1.csv", schema_overrides={"CODE": pl.String})
hhs2 = pl.scan_csv("../data/raw/HouseholdSpend_(HHS)_2025_GEO_P2.csv", schema_overrides={"CODE": pl.String})

# merge hhs1 and hhs2
hhs = hhs1.join(hhs2, on=["CODE", "GEO"], how="inner")

In [3]:
# show descriptive stats

display(demo.describe())
display(hhs.describe())

shape: (9, 737)
┌────────────┬────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ statistic  ┆ CODE   ┆ GEO    ┆ ECYASQKM   ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18 │
│ ---        ┆ ---    ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ P         │
│ str        ┆ str    ┆ str    ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ ---       │
│            ┆        ┆        ┆            ┆   ┆            ┆            ┆            ┆ f64       │
╞════════════╪════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ count      ┆ 950157 ┆ 950157 ┆ 950157.0   ┆ … ┆ 950157.0   ┆ 950157.0   ┆ 950157.0   ┆ 950157.0  │
│ null_count ┆ 0      ┆ 0      ┆ 0.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ mean       ┆ null   ┆ null   ┆ 104.178544 ┆ … ┆ 359.467058 ┆ 60.605155  ┆ 9.745359   ┆ 50.859796 │
│ std        ┆ null   ┆ null   ┆ 13864.5906 ┆ … ┆ 37645.5444 ┆ 6639.49404 ┆ 1069.86785 ┆ 5571.7567 │
│            ┆        ┆        ┆ 39         ┆   ┆ 23         ┆ 6          ┆            ┆ 88        │
│ min        ┆ 000    ┆ CAN    ┆ 0.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ 25%        ┆ null   ┆ null   ┆ 0.0        ┆ … ┆ 7.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ 50%        ┆ null   ┆ null   ┆ 0.0        ┆ … ┆ 18.0       ┆ 1.0        ┆ 0.0        ┆ 1.0       │
│ 75%        ┆ null   ┆ null   ┆ 0.0        ┆ … ┆ 45.0       ┆ 6.0        ┆ 1.0        ┆ 5.0       │
│ max        ┆ Y1A7A4 ┆ REG    ┆ 9.8772e6   ┆ … ┆ 2.9078975e ┆ 4.828559e6 ┆ 776329.0   ┆ 4.05223e6 │
│            ┆        ┆        ┆            ┆   ┆ 7          ┆            ┆            ┆           │
└────────────┴────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

shape: (9, 449)
┌────────────┬────────┬────────┬────────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ statistic  ┆ CODE   ┆ GEO    ┆ HSBASHHD   ┆ … ┆ HSWH016    ┆ HSWH017    ┆ HSWH100    ┆ HSWH101   │
│ ---        ┆ ---    ┆ ---    ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---       │
│ str        ┆ str    ┆ str    ┆ f64        ┆   ┆ f64        ┆ f64        ┆ f64        ┆ f64       │
╞════════════╪════════╪════════╪════════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ count      ┆ 950157 ┆ 950157 ┆ 950157.0   ┆ … ┆ 950157.0   ┆ 950157.0   ┆ 950157.0   ┆ 950157.0  │
│ null_count ┆ 0      ┆ 0      ┆ 0.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ mean       ┆ null   ┆ null   ┆ 201.425804 ┆ … ┆ 1018.74049 ┆ 5130.84475 ┆ 193570.312 ┆ 50433.651 │
│            ┆        ┆        ┆            ┆   ┆ 9          ┆ 2          ┆ 39         ┆ 556       │
│ std        ┆ null   ┆ null   ┆ 21048.4064 ┆ … ┆ 108939.994 ┆ 649016.685 ┆ 2.1192e7   ┆ 5.8358e6  │
│            ┆        ┆        ┆            ┆   ┆ 855        ┆ 616        ┆            ┆           │
│ min        ┆ 000    ┆ CAN    ┆ 0.0        ┆ … ┆ 0.0        ┆ 0.0        ┆ 0.0        ┆ 0.0       │
│ 25%        ┆ null   ┆ null   ┆ 3.0        ┆ … ┆ 5.779185   ┆ 1.703851   ┆ 1735.86435 ┆ 179.11976 │
│            ┆        ┆        ┆            ┆   ┆            ┆            ┆ 6          ┆ 7         │
│ 50%        ┆ null   ┆ null   ┆ 9.0        ┆ … ┆ 30.213625  ┆ 35.049697  ┆ 7533.59281 ┆ 1050.6765 │
│            ┆        ┆        ┆            ┆   ┆            ┆            ┆ 8          ┆ 69        │
│ 75%        ┆ null   ┆ null   ┆ 24.0       ┆ … ┆ 110.758852 ┆ 307.340427 ┆ 23905.0670 ┆ 4482.1635 │
│            ┆        ┆        ┆            ┆   ┆            ┆            ┆ 6          ┆ 06        │
│ max        ┆ Y1A7A4 ┆ REG    ┆ 1.6288077e ┆ … ┆ 8.2310e7   ┆ 4.1266e8   ┆ 1.5578e10  ┆ 4.0367e9  │
│            ┆        ┆        ┆ 7          ┆   ┆            ┆            ┆            ┆           │
└────────────┴────────┴────────┴────────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [4]:
# show demo

demo.head().collect()

shape: (5, 736)
┌──────┬───────┬─────────────┬─────────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CODE ┆ GEO   ┆ ECYASQKM    ┆ ECYALSQKM   ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18P │
│ ---  ┆ ---   ┆ ---         ┆ ---         ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str  ┆ str   ┆ f64         ┆ f64         ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞══════╪═══════╪═════════════╪═════════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 01   ┆ CAN   ┆ 9.8772e6    ┆ 9.5765e6    ┆ … ┆ 29078975   ┆ 4828559    ┆ 776329     ┆ 4052230    │
│ 000  ┆ CMACA ┆ 3.9106e6    ┆ 3.7982e6    ┆ … ┆ 49643      ┆ 1459       ┆ 143        ┆ 1316       │
│ 001  ┆ CMACA ┆ 990.22247   ┆ 951.50766   ┆ … ┆ 180221     ┆ 15980      ┆ 2451       ┆ 13529      │
│ 010  ┆ CMACA ┆ 57.771891   ┆ 55.043757   ┆ … ┆ 11571      ┆ 303        ┆ 62         ┆ 241        │
│ 011  ┆ CMACA ┆ 2658.109183 ┆ 2443.331205 ┆ … ┆ 11088      ┆ 460        ┆ 92         ┆ 368        │
└──────┴───────┴─────────────┴─────────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [5]:
# filter demo to only include rows where GEO contains "PRCDDA"

demo = demo.filter(pl.col("GEO").str.contains("PRCDDA"))

demo.head().collect()

shape: (5, 736)
┌──────────┬────────┬──────────┬───────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ CODE     ┆ GEO    ┆ ECYASQKM ┆ ECYALSQKM ┆ … ┆ ECYTCA_18P ┆ ECYNCANCIT ┆ ECYNCA_U18 ┆ ECYNCA_18P │
│ ---      ┆ ---    ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str      ┆ str    ┆ f64      ┆ f64       ┆   ┆ i64        ┆ i64        ┆ i64        ┆ i64        │
╞══════════╪════════╪══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 10010165 ┆ PRCDDA ┆ 0.38455  ┆ 0.38455   ┆ … ┆ 452        ┆ 0          ┆ 0          ┆ 0          │
│ 10010166 ┆ PRCDDA ┆ 0.095564 ┆ 0.095564  ┆ … ┆ 301        ┆ 0          ┆ 0          ┆ 0          │
│ 10010167 ┆ PRCDDA ┆ 0.126296 ┆ 0.126296  ┆ … ┆ 373        ┆ 52         ┆ 5          ┆ 47         │
│ 10010168 ┆ PRCDDA ┆ 0.191336 ┆ 0.191336  ┆ … ┆ 468        ┆ 43         ┆ 4          ┆ 39         │
│ 10010169 ┆ PRCDDA ┆ 0.06591  ┆ 0.06591   ┆ … ┆ 278        ┆ 0          ┆ 0          ┆ 0          │
└──────────┴────────┴──────────┴───────────┴───┴────────────┴────────────┴────────────┴────────────┘

In [6]:
# show hhs

hhs.head().collect()

shape: (5, 448)
┌──────┬───────┬──────────┬───────────┬───┬──────────────┬──────────────┬───────────┬──────────────┐
│ CODE ┆ GEO   ┆ HSBASHHD ┆ HSHNIAGG  ┆ … ┆ HSWH016      ┆ HSWH017      ┆ HSWH100   ┆ HSWH101      │
│ ---  ┆ ---   ┆ ---      ┆ ---       ┆   ┆ ---          ┆ ---          ┆ ---       ┆ ---          │
│ str  ┆ str   ┆ i64      ┆ f64       ┆   ┆ f64          ┆ f64          ┆ f64       ┆ f64          │
╞══════╪═══════╪══════════╪═══════════╪═══╪══════════════╪══════════════╪═══════════╪══════════════╡
│ 01   ┆ CAN   ┆ 16288077 ┆ 2.0943e12 ┆ … ┆ 8.2310e7     ┆ 4.1266e8     ┆ 1.5578e10 ┆ 4.0367e9     │
│ 000  ┆ CMACA ┆ 24133    ┆ 3.3437e9  ┆ … ┆ 112931.46225 ┆ 582101.27712 ┆ 2.0062e7  ┆ 5.5040e6     │
│      ┆       ┆          ┆           ┆   ┆ 2            ┆ 1            ┆           ┆              │
│ 001  ┆ CMACA ┆ 98080    ┆ 1.2340e10 ┆ … ┆ 49277.76939  ┆ 349050.46145 ┆ 7.8906e7  ┆ 2.2997e7     │
│ 010  ┆ CMACA ┆ 6403     ┆ 6.5841e8  ┆ … ┆ 2252.928934  ┆ 100903.92491 ┆ 3.0151e6  ┆ 656340.60282 │
│      ┆       ┆          ┆           ┆   ┆              ┆              ┆           ┆ 9            │
│ 011  ┆ CMACA ┆ 6155     ┆ 7.1158e8  ┆ … ┆ 3060.835741  ┆ 177233.65637 ┆ 3.6101e6  ┆ 920484.45855 │
│      ┆       ┆          ┆           ┆   ┆              ┆ 6            ┆           ┆ 3            │
└──────┴───────┴──────────┴───────────┴───┴──────────────┴──────────────┴───────────┴──────────────┘

In [7]:
# filter hhs to only include rows where GEO contains "PRCDDA"

hhs = hhs.filter(pl.col("GEO").str.contains("PRCDDA"))

hhs.head().collect()

shape: (5, 448)
┌──────────┬────────┬──────────┬──────────┬───┬───────────┬────────────┬─────────────┬─────────────┐
│ CODE     ┆ GEO    ┆ HSBASHHD ┆ HSHNIAGG ┆ … ┆ HSWH016   ┆ HSWH017    ┆ HSWH100     ┆ HSWH101     │
│ ---      ┆ ---    ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---        ┆ ---         ┆ ---         │
│ str      ┆ str    ┆ i64      ┆ f64      ┆   ┆ f64       ┆ f64        ┆ f64         ┆ f64         │
╞══════════╪════════╪══════════╪══════════╪═══╪═══════════╪════════════╪═════════════╪═════════════╡
│ 10010165 ┆ PRCDDA ┆ 227      ┆ 2.6823e7 ┆ … ┆ 81.880915 ┆ 238.14635  ┆ 213747.5082 ┆ 50801.20193 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 13          ┆ 8           │
│ 10010166 ┆ PRCDDA ┆ 148      ┆ 2.0631e7 ┆ … ┆ 38.105455 ┆ 150.123809 ┆ 132661.6488 ┆ 26581.57664 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 53          ┆ 3           │
│ 10010167 ┆ PRCDDA ┆ 217      ┆ 2.4982e7 ┆ … ┆ 55.752517 ┆ 274.405589 ┆ 192554.9718 ┆ 27863.83421 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 51          ┆ 8           │
│ 10010168 ┆ PRCDDA ┆ 256      ┆ 2.9207e7 ┆ … ┆ 64.164596 ┆ 272.749813 ┆ 225708.3181 ┆ 37569.18016 │
│          ┆        ┆          ┆          ┆   ┆           ┆            ┆ 3           ┆ 6           │
│ 10010169 ┆ PRCDDA ┆ 132      ┆ 1.4251e7 ┆ … ┆ 37.345065 ┆ 163.203105 ┆ 98971.15476 ┆ 9061.92496  │
└──────────┴────────┴──────────┴──────────┴───┴───────────┴────────────┴─────────────┴─────────────┘